[build]
  image = "cuda-build:latest"

[[run.images]][[order.group]]
    id = "paketo-buildpacks/java"
  image = "cuda-run:latest"

[[buildpacks]]
  uri = "docker.io/paketobuildpacks/java"

[[targets]]
  os = "linux"
  arch = "amd64"

[[order]]
  [[order.group]]
    id = "paketo-buildpacks/java"

